site_name: shebik | Programmer
site_url: https://shelbyen.github.io/
site_author: shebik
site_description: Full Stack Developer & Problem Solver

# Theme configuration
theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate

# Navigation
site_name: Мое Портфолио

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Лабораторная 1: labs/lab1.md
      # - Лабораторная 2: labs/lab2.md
      # - Лабораторная 3: labs/lab3.md
      # - Лабораторная 4: labs/lab4.md
      # - Лабораторная 5: labs/lab5.md

# Copyright
copyright: Copyright &copy; 2023 shebik. All code is poetry.
